version: '3'
services:
  frontend:
    build: ./frontend
    container_name: app-frontend
    restart: unless-stopped
    command: serve -s build -l 3000

  api:
    build: ./api
    container_name: app-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://app-test.com
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db

  auth:
    build: ./auth
    container_name: app-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://app-test.com
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db

  api_db:
    image: mongo:latest
    container_name: app-api_db
    volumes:
      - mongodb_api:/data/db

  auth_db:
    image: mongo:latest
    container_name: app-auth_db
    volumes:
      - mongodb_auth:/data/db

  nginx:
    image: nginx:stable-alpine
    container_name: app-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend

volumes:
  mongodb_api:
  mongodb_auth:


